bufferapp/app-shell

- src/NavBar/index.jsx
Replace social accounts by channels in the org switcher.
https://buffer.atlassian.net/browse/PUB-3032
> [PUB-3032] Update channels copy in Org Switcher

- src/NavBar/index.jsx
Simplify appendOrgSwitcher function and fix bug with icons
> Simplify menu items

- packages/app-shell/.storybook/main.js
- packages/app-shell/.storybook/preview.js
- packages/app-shell/package.json
- packages/app-shell/src/PlanSelector/components/SelectionScreen.jsx
- packages/app-shell/src/PlanSelector/components/SelectionScreen.stories.js
- yarn.lock
Adds storybook to the app-shell directory so we can build and test to UI for the plan selector
To start storybook, go to `app-shell/packages/app-shell` and run `yarn storybook`
> add storybook with an example story for plan selector

- CHANGELOG.md
- packages/app-shell/package.json
- packages/app-shell/src/Modal/index.jsx
- packages/app-shell/src/PaymentMethod/components/Field.jsx
- packages/app-shell/src/PaymentMethod/components/Form.jsx
- packages/app-shell/src/PaymentMethod/components/StripeProvider.jsx
- packages/app-shell/src/PaymentMethod/hooks/useCreatePaymentMethod.js
- packages/app-shell/src/PaymentMethod/hooks/useCreatePaymentMethod.test.js
- packages/app-shell/src/PaymentMethod/hooks/useSetupIntent.js
- packages/app-shell/src/PaymentMethod/hooks/useSetupIntent.test.jsx
- packages/app-shell/src/PaymentMethod/hooks/useUpdateSubscriptionPlan.js
- packages/app-shell/src/PaymentMethod/hooks/useUpdateSubscriptionPlan.test.jsx
- packages/app-shell/src/PaymentMethod/hooks/useUpdateUserPaymentMethod.js
- packages/app-shell/src/PaymentMethod/hooks/useUpdateUserPaymentMethod.test.jsx
- packages/app-shell/src/PaymentMethod/index.jsx
- packages/app-shell/src/PaymentMethod/style.js
- packages/app-shell/src/graphql/billing.js
- packages/app-shell/src/hooks/useModal.js
- packages/app-shell/src/hooks/useModal.test.js
- packages/app-shell/src/index.jsx
- yarn.lock
To add the Payment Method Modal
[(ref.)](https://www.figma.com/file/D81vy7rYgF1dd8xvV8UsrQ/Buffer-Plan-Selector?node-id=651%3A37993)
> Payment Method Modal

- packages/app-shell/src/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/PlanSelector/index.jsx
- packages/app-shell/src/PlanSelector/style.js
Adds a loading state to the plan selector if we need to wait for planOptions and adds max width to the cards
This is what the loading state looks like: https://share.buffer.com/4gu1q1nO
> add loading state to planSelector and max width to cards

- packages/app-shell/src/Confirmation/index.jsx
- packages/app-shell/src/PaymentMethod/style.js
- packages/app-shell/src/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/PlanSelector/hooks/useButtonOptions.js
- packages/app-shell/src/PlanSelector/hooks/useHeaderLabel.js
- packages/app-shell/src/PlanSelector/hooks/useInterval.js
- packages/app-shell/src/PlanSelector/hooks/useInterval.test.jsx
- packages/app-shell/src/PlanSelector/hooks/useSelectedPlan.js
- packages/app-shell/src/PlanSelector/hooks/useSelectedPlan.test.jsx
- packages/app-shell/src/PlanSelector/index.jsx
- packages/app-shell/src/StartTrial/style.js
- packages/app-shell/src/Summary/index.jsx
- packages/app-shell/src/Summary/style.js
- packages/app-shell/src/mocks/freePlan.js
the commits have the details!
https://paper.dropbox.com/doc/Plan-Selector-Design-Feedback--BHDsC2dQsZDZwvt09Z_B_Xs~Ag-gvxiRx7vvKC2XaEzkrbeQ
> Plan Selector QA 2

- CHANGELOG.md
- packages/app-shell/src/index.jsx
Handle the redirect to login in the app-shell if the user does not have an account
> Redirect to logout url if account has an error state

- packages/app-shell/src/PaymentMethod/components/Form.jsx
- packages/app-shell/src/PaymentMethod/index.jsx
- packages/app-shell/src/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/PlanSelector/components/SelectionScreen.jsx
- packages/app-shell/src/PlanSelector/hooks/useButtonOptions.js
- packages/app-shell/src/PlanSelector/hooks/useButtonOptions.test.jsx
- packages/app-shell/src/PlanSelector/hooks/useHeaderLabel.js
- packages/app-shell/src/PlanSelector/hooks/useHeaderLabel.test.jsx
- packages/app-shell/src/PlanSelector/hooks/useInterval.js
- packages/app-shell/src/PlanSelector/hooks/useSelectedPlan.js
- packages/app-shell/src/PlanSelector/hooks/useSelectedPlan.test.jsx
- packages/app-shell/src/PlanSelector/index.jsx
- packages/app-shell/src/PlanSelector/style.js
- packages/app-shell/src/Summary/index.jsx
- packages/app-shell/src/Summary/style.js
- packages/app-shell/src/graphql/account.js
- packages/app/src/App.js
see the commits for details :)
> Plan Selector QA 4

- README.md
Adding some light documentation on how to use the plan selector as folks starting implementing it in their apps :)
> update documentation to include plan selector usage

- README.md
> fix the intention example

- packages/app-shell/src/PaymentMethod/components/Field.jsx
- packages/app-shell/src/PaymentMethod/components/StripeProvider.jsx
- packages/app-shell/src/PaymentMethod/index.jsx
- packages/app-shell/src/PaymentMethod/style.js
- packages/app-shell/src/PlanSelector/index.jsx
fixes:
- Stripe production key
- rendering plan selector from URL
- rendering payment method from URL
- payment method top level error style
> Fix Plan Selector and Payment Method modals

- packages/app-shell/src/PaymentMethod/style.js
- packages/app-shell/src/PlanSelector/style.js
- packages/app-shell/src/graphql/account.js
- packages/app-shell/src/index.jsx
Adds the trial banner in the app-shell:
> add trial banner to app shell

- packages/app-shell/src/index.jsx
- packages/app/src/App.js
each app will deal with MP users in their own apps
> make trial banner only show up for OB users

- packages/app-shell/src/Modal/index.jsx
- packages/app-shell/src/index.jsx
https://buffer.atlassian.net/browse/AT-889
> render plan selector on isAwaitingUserAction

- packages/app-shell/src/graphql/account.js
Expands the information under the user object needed for Analyze.
> Query for organization feature flips and MP subscriptions

- packages/app-shell/src/PaymentMethod/hooks/useSetupIntent.test.jsx
- packages/app-shell/src/PaymentMethod/hooks/useUpdateUserPaymentMethod.test.jsx
- packages/app-shell/src/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/StartTrial/index.jsx
- packages/app-shell/src/hooks/useStartTrial.js
- packages/app-shell/src/hooks/useStartTrial.test.js
- packages/app-shell/src/index.jsx
This is the same as https://github.com/bufferapp/app-shell/pull/51, just that I messed that one up and erased all the work. Luckily, I had this one 😬
> move start trial mutation to a hook and expose on appshell

- packages/app-shell/src/PaymentMethod/components/Form.jsx
- packages/app-shell/src/PaymentMethod/hooks/useCreatePaymentMethod.js
- packages/app-shell/src/PaymentMethod/hooks/useCreatePaymentMethod.test.js
- packages/app-shell/src/PaymentMethod/style.js
Properly submit the Payment Method form when pressing **Enter**.
> properly submit payment method modal on Enter

- packages/app-shell/package.json
- packages/app-shell/src/PaymentMethod/style.js
- packages/app-shell/src/PlanSelector/components/SelectionScreen.jsx
- packages/app-shell/src/PlanSelector/style.js
- packages/app-shell/src/Summary/index.jsx
- packages/app-shell/src/Summary/style.js
- yarn.lock
Fixes:
- Plan Selector → Design feedback tweaks
- Billing Screen → The summary box is looking pretty squashed here compared to the plan selector screen
- fix vertical centering of the modals
> Plan Selector UI polishing

- packages/app-shell/src/graphql/account.js
removing the interval from the query as it was causing problems with the query resolution
> remove subscription interval from query

- packages/app-shell/src/hooks/useUserTracker.js
- packages/app-shell/src/hooks/utils/segmentTraitGetters.js
- packages/app-shell/src/hooks/utils/segmentTraitGetters.test.js
Track the `isFreePlan` trait in the `identify` call
> add isFreePlan trait

- packages/app-shell/src/NavBar/components/UpgradeCTA.jsx
- packages/app-shell/src/NavBar/index.jsx
fix upgrade CTA url for MP Publish
> fix CTAs for legacy users

- packages/app-shell/src/NavBar/index.jsx
- packages/app-shell/src/index.jsx
Should be an object reference instead of a string.
> Fix `apolloClient` propType 

- packages/app-shell/src/NavBar/index.jsx
- packages/app-shell/src/graphql/account.js
To show the channels list in the org switcher.
> show channels in org switcher

- packages/app-shell/src/components/Modal/index.jsx
use `user.loading` instead of `user.load` bug introduced in #82
> Fix Trial Expired rendering

- packages/app-shell/src/common/graphql/account.js
- packages/app-shell/src/common/hooks/useUserTracker.js
- packages/app-shell/src/common/hooks/useUserTracker.test.js
- packages/app-shell/src/common/hooks/utils/segmentTraitGetters.js
- packages/app-shell/src/common/hooks/utils/segmentTraitGetters.test.js
To add paidSubscriptionAutoRenewEnabled trait to identify
[GROW-171](https://buffer.atlassian.net/browse/GROW-171)
> add paidSubscriptionAutoRenewEnabled trait to identify [GROW-171]

- .github/workflows/cypress.yml
- README.md
- cypress.json
- cypress/fixtures/account.json
- cypress/fixtures/accountObEssential.json
- cypress/fixtures/accountObFree.json
- cypress/fixtures/accountObTeam.json
- cypress/integration/navigator/navigator.spec.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- jest.config.json
- local.json
- package.json
- packages/app-shell/src/components/NavBar/components/UpgradeCTA.jsx
- yarn.lock
UX testing are integration tests meant to ensure that the entire app behaves as expected in its entirety on all the various scenarios (Account types, billing states, …).
All integrations tests are contained in the `./cypress/integration` folder.
- We want to tests complex core flows. For example: that a specifix CTA is properly showing for a subset of users, or that the billing flow can be fully executed.
- do not test for a specific copy. This type of tests are quite brittle, on honestly not that useful. Instead, use static `#ids` to test for the presence of a specific component
Ex:
```js
it('has an invite team CTA', () => {
cy.get('#inviteTeamCTA')
.should('exist')
})
```
- do not test the entire APIs flow (login, user fetching). While those tests can be very valuable (we have Synthetic …
> Add Cypress tests

- .github/workflows/upload.yml
- .travis.yml
- package.json
- packages/app-shell/src/components/NavBar/components/NavBarProducts/NavBarProducts.jsx
- packages/app-shell/src/components/NavBar/index.jsx
I've begun work on GROW-195 and noticed there were a few eslint errors that could be fixed along the way.
I decided to split my PR up to hopefully make the changes easier to read and also get an understanding for how PRs work in the team  😀
This PR only fixes eslint errors and adds 2 new commands to the package.json which allows you to:
1. run eslint on the whole repo
2. just on the files you have touched.
Notes:
I think Prettier has done some auto fixing and not sure if this is correct, or I've got some conflicting configs 😄
> Cleanup eslint errors

- packages/app-shell/src/components/Modal/modals/PaidMigration/EssentialsPlan/style.js
The features table in the OB migration modal looks a bit off. Sending a fix for it.
> CSS Fix for features table on essentials plan modal

- packages/app-shell/src/components/Modal/modals/PaidMigration/EssentialsPlan/style.js
This PR fixes styling inconsistencies on the OB migration modal UX between different product pages and also browsers.
> Styling fix for OB migration modal

- .eslintrc.js
- packages/app-shell/src/components/Modal/index.jsx
Reverts bufferapp/app-shell#101
> Revert "Hide migration modal if Pendo guide is visible"

- packages/app-shell/src/exports/Navigator/index.jsx
Changing the copy of the banner as it was stated in an older ticket. It seems that this copy changed slipped through back then. 
https://buffer.atlassian.net/browse/GROW-53
NOTE: There is some prettier auto formatting in the file. I left a comment in the 2 lines of the actual changes.
> [GROW-53] Update the trial banner copy and billing details CTA

- packages/app-shell/src/components/NavBar/utils/dropdown-items.js
https://buffer.atlassian.net/browse/GROW-243
Adding an "Integrations" link.
> [GROW-243] Add Integrations Link

- packages/app-shell/src/components/NavBar/components/BufferLogoWithWords.jsx
https://buffer.atlassian.net/browse/GROW-223﻿
> [GROW-223] Make Buffer logo link to Publishing

- README.md
Just updating the readme file to remove some npm steps that are no longer needed :)
> Update readme to remove outdated steps

- cypress/fixtures/accountObFreeNoChannels.json
- packages/app-shell/src/common/mocks/accountOBFree.js
- packages/app-shell/src/components/Modal/modals/ChannelConnectionPrompt/index.jsx
- packages/app-shell/src/components/Modal/utils.js
- packages/app-shell/src/components/Modal/utils.test.jsx
remove newProductsOnboarding feature flip
> WEBAPP-273 remove newProductsOnboarding  FF

- packages/app-shell/src/components/Modal/modals/ChannelConnectionPrompt/index.jsx
Small change according to the [Figma Design File](https://www.figma.com/file/ugvq6I5lJ07W1aJBJg4ihm/Onboarding-2022?node-id=1239%3A74704)
After:
Before:
> [WEBAPP-224] Change modal connection copy change for Engagement

- packages/app-shell/src/components/NavBar/utils/dropdown-items.js
Add new `Changelog` menu item under the `Help` menu as requested by Marketing in this [thread](https://threads.com/34418397398).
> [WEBAPP-367] Add new Changelog menu item

- README.md
Adding instructions on how to use Storybook for AppShell components
> Include instructions for Storybook

- packages/app-shell/src/components/Modal/modals/QuantityUpdate/QuantityUpdate.stories.js
- packages/app-shell/src/components/Modal/modals/QuantityUpdate/index.jsx
- packages/app-shell/src/components/Modal/modals/QuantityUpdate/style.js
Small styling update to the Quantity modal 
Created a storybook for this component
> Styling update for new Quantity Update modal

- packages/app-shell/src/components/NavBar/utils/dropdown-items.js
We are adding a new item to the Help menu which, when clicked, will trigger a Pendo guide to help customers getting started with Buffer.
[Jira ticket](https://buffer.atlassian.net/browse/COREP-437)
> [COREP-437] Add new 'Getting Started' menu item

- cypress/fixtures/accountObFreeUpgrade.json
- cypress/integration/navigator/navigator.spec.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/SelectionScreen.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useInterval.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useInterval.test.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useSelectedPlan.js
- packages/app-shell/src/components/Modal/utils.js
- packages/app-shell/src/components/Modal/utils.test.jsx
Reverts bufferapp/app-shell#172
This PR re-reverts the change which we thought cause this incident https://github.com/bufferapp/app-shell/pull/172
> Revert "Revert "Task/grow 389 fix upgrade bug""

- packages/app-shell/src/components/Modal/index.jsx
Reverts bufferapp/app-shell#185
breaks background layouts
> Revert "Fix/z index modals"

- packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/index.jsx
Jira: https://buffer.atlassian.net/browse/GROW-417
This prevents the success modal from appearing when a user only updates there channel amount but stays on the same plan.
> [UPDATE] new check if user stayed on same plan

- packages/app-shell/src/common/hooks/useChannelsCounter.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx
JIRA: [GROW-436](https://buffer.atlassian.net/browse/GROW-436)
Swicthes the selected plan to essentials when free plan selected and user tries to increase above 3
> [UPDATE] switch selected plan to essentials

- cypress/fixtures/accountObEssential.json
- cypress/fixtures/accountObEssentialNoChannels.json
- cypress/fixtures/accountObFree.json
- cypress/fixtures/accountObFreeUpgrade.json
- cypress/fixtures/accountObTeam.json
- packages/app-shell/src/common/graphql/account.js
- packages/app-shell/src/components/Modal/modals/PaymentMethod/index.jsx
Updates to use `canManageBilling` from the `privileges` field on `AccountOrganization`.
> Use updated canManageBilling from privileges

- cypress/fixtures/accountObEssential.json
- cypress/fixtures/accountObEssentialNoChannels.json
- cypress/fixtures/accountObFree.json
- cypress/fixtures/accountObFreeUpgrade.json
- cypress/fixtures/accountObTeam.json
Added missing key value pair from data
> [FIX] Failing cypress tests

- package.json
- yarn.lock
Upgrading in an attempt to fix the flakey cypress test which fails frequently in our pipelines
> [UPDATE] Up[grade cypress to 9.5.2

- cypress/fixtures/accountObEssential.json
- cypress/integration/modal/quantityupdate.spec.js
- packages/app-shell/src/components/Modal/modals/Confirmation/index.jsx
- packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
- packages/app/src/App.js
Adding happy path test for Quantity Update modal
https://user-images.githubusercontent.com/1514227/160392550-a3eb4915-f753-44e4-adde-0874d4596bea.mov
> [GROW-448] add cypress test for quantity update happy path

- packages/app-shell/src/components/NavBar/components/BufferLogoWithWords.jsx
This PR adds the Ukrainian flag 🇺🇦 next to the Buffer Logo
> Add ukrainian flag 🇺🇦

- packages/app-shell/src/components/NavBar/components/BufferLogoWithWords.jsx
> Replace 🇺🇦 emoji with CSS background

- cypress/fixtures/accountObAgency.json
Manually updated fixture using the query locally in https://graph.local.buffer.com/: 
```
query {
account {
id
email
createdAt
featureFlips
isImpersonation
shouldShowEmailVerificationCommunication
currentOrganization {
id
name
canEdit
privileges {
canManageBilling
__typename
}
role
createdAt
isOneBufferOrganization
canMigrateToOneBuffer {
canMigrate
reasons
__typename
}
shouldDisplayInviteCTA
featureFlips
channels {
id
name
service
organizationId
__typename
}
billing {
id
canAccessAnalytics
canAccessEngagement
canAccessPublishing
paymentDetails {
hasPaymentDetails
__typename
}
... on MPBilling {
billingRedirectUrl
subscriptions {
interval
plan
product
trial {
isActive
__typename
}
__typename
}
__typename
}
__typename
... on OBBilling {
canStartTrial
subscription {
quantity
interval …
```
> [GROW-434] Update Agency fixture
