- CHANGELOG.md
- src/NavBar/index.jsx
Fix code regression caused when transferring the app-shell from the ui to its own package.
Menu items are missing some information: channels icons, empty state message
> Fix org switcher menu items

- CHANGELOG.md
- src/NavBar/index.jsx
Allows the org switcher to include a `hideTooltips` property in order to hide tool tips (channels info) when a user hovers over that organization in the org switcher. 
The org switcher provides a list of channels associated with an organization when a user hovers over that organization. If no channels have been connected yet, then it defaults to a tooltip message that reads, `No channels connected yet.`. For the global org switcher, we do not yet have shared channels in place so we need a way to hide these tooltips for now. 
**Before:**
**After:**
> Allow hiding of tooltip message within the org switcher

- src/NavBar/NavBarProducts/NavBarProducts.jsx
- src/index.jsx
This PR has the changes needed to always make the `Engagement` link point to `https://engage.buffer.com`, removing the decision of redirecting the user to the signup page if needed. 
Initially users without an `engage` product link would be redirected so they can perform a signup first but, we have an extra step now, based on the `canAccessEngagement` value so users under a free plan are redirected to `https://engage.buffer.com/free-plan`. Ideally this kind of decisions should be made on the App Shell to avoid extra redirects but that's not easy for now. We will make that improvement once the smart App Shell is ready 🙂
> Update 'Engagement' URL

- packages/app/package.json
This is needed so that the dev server can be piped from a VM, the app shell will still be available on `appshell.local.buffer.com`
> change host url to 0.0.0.0

- CHANGELOG.md
- packages/app-shell/package.json
- packages/app-shell/src/graphql/account.js
To add canAccess* flags to the organizations an account belongs to:
- `canAccessAnalytics`
- `canAccessEngagement`
- `canAccessPublishing`
> Get access flags for the organizations the account belongs to

- packages/app-shell/src/NavBar/components/UpgradeCTA.jsx
- packages/app-shell/src/graphql/account.js
**What**
Add missing account query fields: since we update the cache manually when we select an org, the organizations object has to return the same fields as the currentOrganization one.
This is just a temporary fix, we're fixing the mutation (as mentioned in the [Apollo Mutation thread](https://threads.com/34393830700))
> Add missing account query fields

- CHANGELOG.md
- packages/app-shell/src/index.jsx
401 error makes more sense for unauthorized, so I'll reach out to Core around whether we can get this changed.
> Change 400 error redirect to 401

- packages/app-shell/src/NavBar/components/UpgradeCTA.jsx
forgot to add this is my last PR but that upgrade CTA will always be with the intent to upgrade 😅
> set upgrade intent in navbar CTA

- packages/app-shell/src/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/PlanSelector/style.js
- packages/app-shell/src/graphql/account.js
Displays the downgraded to free messages, when the subscription is downgraded to free from a paid, but it will be canceled by the end of the current billing period. 
@gmzjuliana take a good look at the css. I just copied pieces from the other parts of the application to make it look like design.
> [AT-891] Display the downgraded to free message in plan selector

- README.md
- packages/app-shell/src/Confirmation/index.jsx
- packages/app-shell/src/Modal/index.jsx
- packages/app-shell/src/NavBar/components/UpgradeCTA.jsx
- packages/app-shell/src/PaymentMethod/index.jsx
- packages/app-shell/src/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/PlanSelector/hooks/useButtonOptions.js
- packages/app-shell/src/StartTrial/index.jsx
- packages/app-shell/src/hooks/useSegmentTracking.js
- packages/app-shell/src/hooks/useSegmentTracking.test.js
- packages/app/src/App.js
Uses the `getProductPath ` method to extract the product name from the url, instead of the `PRODUCT_TRACKING_KEY` global.
> Extract the product name from the url for tracking

- packages/app-shell/src/PaymentMethod/components/Form.jsx
- packages/app-shell/src/PaymentMethod/hooks/useCreatePaymentMethod.js
- packages/app-shell/src/StartTrial/index.jsx
fixes:
- No error message displayed when the very first API call (createSetupIntent) errors
- Confirm Payment Details CTA remains disabled after an error
- Uncaught TypeError: Cannot read property 'billingStartTrial' of undefined
[ref.](https://paper.dropbox.com/doc/One-Buffer-ANZ-Launch-QA-Issue-Tracking--BIVOHMRf2H3FifcVx21z5ACnAg-qQdBQN91aoL7nbJ6yayaa)
> Fix start trial and payment methods retry

- packages/app-shell/src/hooks/useOrgSwitcher.js
While I tried to use the org-switcher in production in https://account.buffer.com, I got the following error
I tried with the analytics app and I got that as well, while trying to impersonate several users and I was able to get the error quite often. When I tried to simulate the error locally it pointed to the apollo client query and this is how I found this line. 
I believe I understand what is happening and I have a theory, but I was not able to think of a proper solution and therefore this "defensive" patch that at least prevents the error and recovers the functionality. 
I have some assumptions though 😅 
In the analytics app we have other graphql queries as well for the account, one for fetching the `canAccessAnalytics` flag, which is not needed anymore and one for fetching the …
> Default potentially null query data when updating cache

- packages/app-shell/src/Confirmation/getCopy.js
- packages/app-shell/src/Confirmation/getCopy.test.jsx
- packages/app-shell/src/PaymentMethod/components/Form.jsx
- packages/app-shell/src/PlanSelector/components/SelectionScreen.jsx
- packages/app-shell/src/PlanSelector/hooks/useButtonOptions.js
- packages/app-shell/src/PlanSelector/hooks/useHeaderLabel.js
- packages/app-shell/src/PlanSelector/hooks/useHeaderLabel.test.jsx
- packages/app-shell/src/PlanSelector/style.js
- packages/app-shell/src/StartTrial/index.jsx
- packages/app-shell/src/StartTrial/style.js
- packages/app-shell/src/Summary/index.jsx
- packages/app-shell/src/Summary/style.js
- packages/app-shell/src/index.jsx
In this edition: 
- fix spacing and button copy in Start Trial modal
- tweaks to the trial banner display logic (show on trial, to admins, when there's not billing info)
- style tweaks to the plan selector cards and summary
- summary logic tweaks to summary note
> Plan Selector Tweaks 5

- README.md
- packages/app-shell/src/Confirmation/getCopy.test.jsx
- packages/app-shell/src/PlanSelector/hooks/useButtonOptions.test.jsx
- packages/app-shell/src/PlanSelector/hooks/useHeaderLabel.test.jsx
- packages/app-shell/src/PlanSelector/hooks/useInterval.test.jsx
- packages/app-shell/src/PlanSelector/hooks/useSelectedPlan.test.jsx
- packages/app-shell/src/Summary/index.jsx
- packages/app-shell/src/hooks/useSegmentTracking.test.js
- packages/app-shell/src/hooks/useUpdateSubscriptionPlan.test.jsx
- packages/app-shell/src/mocks/mock.js
Renames the individual plan instances to essentials.
This change has a server side dependency https://github.com/bufferapp/core-authentication-service/pull/912
> Rename individual plan instances to essentials

- packages/app-shell/src/PaymentMethod/components/Form.jsx
- packages/app-shell/src/Summary/index.jsx
- Show all trial users the summary note that they won't be charged till the end of their trial
- fix stripe copy in payment method
> Summary note and copy tweaks

- packages/app-shell/src/graphql/account.js
- packages/app-shell/src/index.jsx
This is a temporary solution, we will need to fix this on the BE, making sure the `trial` is set to `null`, when missing for `MPUsers` instead of getting omitted.
> remove the MPBilling trial field that was preventing the query from resolving

- packages/app-shell/src/graphql/account.js
This fixes the issue with the `trial` and `interval` fields causing the queries to fail.
The problem was caused by Apollo Cache failing to resolving the subscription data because those fields were only present in the `currentOrganization` query but not in the `organization`.
We really need to start returning `id` for all the relevant fields to avoid this issue.
> return MPSubscription trial and Subscription interval

- packages/app-shell/.storybook/main.js
- packages/app-shell/.storybook/preview.js
- packages/app-shell/package.json
- packages/app-shell/src/Confirmation/getCopy.js
- packages/app-shell/src/Confirmation/index.jsx
- packages/app-shell/src/NavBar/components/UpgradeCTA.jsx
- packages/app-shell/src/NavBar/index.jsx
- packages/app-shell/src/PaymentMethod/PaymentMethod.stories.js
- packages/app-shell/src/PaymentMethod/style.js
- packages/app-shell/src/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/PlanSelector/components/PlanSelectorContainer.stories.js
- packages/app-shell/src/PlanSelector/components/SelectionScreen.jsx
- packages/app-shell/src/PlanSelector/hooks/useInterval.js
- packages/app-shell/src/PlanSelector/hooks/useInterval.test.jsx
- packages/app-shell/src/PlanSelector/style.js
- packages/app-shell/src/Summary/Summary.stories.js
- packages/app-shell/src/Summary/index.jsx
- packages/app-shell/src/Summary/style.js
- packages/app-shell/src/graphql/account.js
- packages/app-shell/src/hooks/useUserTracker.js
- packages/app-shell/src/hooks/useUserTracker.test.js
- packages/app-shell/src/hooks/utils/segmentTraitGetters.js
- packages/app-shell/src/hooks/utils/segmentTraitGetters.test.js
- yarn.lock
- [[GROW-18](https://buffer.atlassian.net/browse/GROW-18)] default plan selector to annual pricing when upgrading
- track `organizationUserRole`
- [[GROW-53](https://buffer.atlassian.net/browse/GROW-53)] Remove the "You will be charged after trial" message from the plan selector
- [[GROW-12](https://buffer.atlassian.net/browse/GROW-12)] Plan selector tweaks, depends on https://github.com/bufferapp/core-authentication-service/pull/1008
- [[GROW-8](https://buffer.atlassian.net/browse/GROW-8)] Optimize UX for Invoice access in the Plan Selector
- [[GROW-23](https://buffer.atlassian.net/browse/GROW-23)] Persistent CTAs in top nav for OB/MP
- [[GROW-14](https://buffer.atlassian.net/browse/GROW-14)] Add Invite your Team CTA to Appshell, depends on …
> Plan selector updgrades

- packages/app-shell/src/NavBar/index.jsx
This fixes the `start free trial` CTA in the dropdown menu, if was opening the plan selector instead of the start trial modal
> fix start trial menu CTA

- packages/app-shell/src/Modal/index.jsx
- packages/app-shell/src/TrialExpired/TrialExpired.stories.jsx
- packages/app-shell/src/TrialExpired/index.jsx
- packages/app-shell/src/hooks/useModal.js
- packages/app-shell/src/index.jsx
- packages/app-shell/src/mocks/trialExpiredMock.js
- packages/app-shell/src/utils/cookies.js
- packages/app/public/index.html
To show the trial expired modal if a user terminated is trial [[GROW-5]](https://buffer.atlassian.net/browse/GROW-5).
Once the modal is dismissed it won't be visible, on the same browser, for 2 months.
If you want to test this without setting up the user you can show the modal typing `window.appshell.actions.openModal(window.appshell.MODALS.trialExpired)` in the  browser dev console.
[GROW-5]: https://buffer.atlassian.net/browse/GROW-5
> Add trial expired modal [GROW-5]

- packages/app-shell/src/common/hooks/useModal.js
- packages/app-shell/src/common/hooks/useOrgSwitcher.js
- packages/app-shell/src/exports/navigator.js
This expose the `setCurrentOrganization` action so that product apps can trigger the organization change outside of the Navigator.
This is needed to allow Publishing to change the org based on the url.
>  expose setCurrentOrganization action

- packages/app-shell/src/components/Modal/index.jsx
Make sure the user data has been load before processing the trial expired modal conditions
> fix trial expired modal

- packages/app-shell/src/common/utils/cookies.js
- packages/app-shell/src/components/Modal/modals/TrialExpired/index.jsx
store trial expired modal dismiss on both CTAs, and set a root domain  cookie
> always set cookies for Trial Expired Modal

- packages/app-shell/src/components/NavBar/components/UpgradeCTA.jsx
Updated the Upgrade CTA URL to https://publish.buffer.com/plans for free non trial users. 
[[GROW-172]](https://buffer.atlassian.net/browse/GROW-172)
[GROW-172]: https://buffer.atlassian.net/browse/GROW-172
> Updated Upgrade CTA URL [GROW-172]

- README.md
- package.json
- packages/app/package.json
This updates the readme, and adds `yarn watch-procution` to run the AppShell in dev mode against production APIs Gateway.
> Update README, and add watch-production mode

- packages/app-shell/src/common/graphql/billing.js
- packages/app-shell/src/common/hooks/useOrgSwitcher.js
- packages/app-shell/src/common/hooks/useSegmentTracking.js
- packages/app-shell/src/common/hooks/useSegmentTracking.test.js
- packages/app-shell/src/common/hooks/useStartTrial.js
- packages/app-shell/src/common/hooks/useUpdateSubscriptionPlan.js
- packages/app-shell/src/common/hooks/useUpdateSubscriptionPlan.test.jsx
- packages/app-shell/src/common/utils/getProduct.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/components/Modal/modals/StartTrial/index.jsx
This properly pass down `attribution` to the `trialStart` and `updateSubscription` migrations  [GROW-190](https://buffer.atlassian.net/browse/GROW-190).
It also fixes the missing product in the `organizationSwitched` event
> GROW-190 properly pass CTAs for upgrade and trial start

- packages/app-shell/src/components/Modal/modals/PaymentMethod/index.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/components/Modal/modals/StartTrial/index.jsx
- packages/app-shell/src/components/Modal/modals/TrialExpired/index.jsx
- packages/app-shell/src/components/NavBar/components/UpgradeCTA.jsx
- packages/app-shell/src/components/NavBar/index.jsx
- packages/app-shell/src/exports/Navigator/index.jsx
This fixes missing CTAs, and prevent CTAs overrides when moving between the various modals of the plan selector flow.
> fix missing ctas

- packages/app-shell/src/components/NavBar/components/NavBarProducts/NavBarProducts.jsx
Engagement will no longer be our newest feature when we launch Canva, so it's time to say farewell to the "New!" label next to Engagement in the Appshell. 👋
Jira ticket: [Remove "New" label from Engagement in the Appshell](https://buffer.atlassian.net/browse/PUB-3761)
> [PUB-3761] Remove new label for Engagement

- packages/app-shell/src/common/graphql/account.js
This is patching the issue with the org switching reported in slack https://buffer.slack.com/archives/C0DLE125Q/p1629295586196200
> Add the canMigrateToOneBuffer node to the organizations query

- .eslintrc.js
- packages/app-shell/src/components/Modal/index.jsx
If there is a Pendo guide in place on the page it overlaps the OB migration modal. Talking to Tom and James about it we decided it would be great to only display the migration modal if there are no Pendo guides visible.
I'm using a function in Pendo's script called `pendo.isGuideShown()` to check if any Pendo guides are up on the page. I don't have a ton of context about how Pendo works and I couldn't find any documentation on all the functions available so I'm not sure if this covers all cases.
> Hide migration modal if Pendo guide is visible

- .eslintrc.js
- packages/app-shell/src/components/Modal/index.jsx
If there is a Pendo guide in place on the page it overlaps the OB migration modal. Talking to Tom and James about it we decided it would be great to only display the migration modal if there are no Pendo guides visible.
I'm using a function in Pendo's API called `pendo.isGuideShown()` to check if any Pendo guides are up on the page. I don't have a ton of context about how Pendo works and I couldn't find any documentation on all the functions available so I'm not sure if this covers all cases.
> Don't show OB migration modal if Pendo guide is visible

- packages/app-shell/src/exports/Navigator/index.jsx
`Team` is not a plan that we return anymore. We have `Essentials` and `Essentials + Team`. 
I made this fix here to fix the issue for the production, but we should perhaps let the backend generate that string and use it as we get it, then we don't have to maintain the logic here.
> Fix the plan name in the trial banner

- .eslintrc.js
- package.json
- yarn.lock
This removes many eslint errors when working in testing files
This PR installed a new package at the root level `"eslint-plugin-cypress": "^2.11.3",` and updates the `.eslintconfig` to handle test packages.
This was installed this to get rid of a large amount of eslint errors which are in the package due to test files using jest and cypress
This helps reduce/fix errors that appear if you run `yarn run lint` in the repo, from 674 problems down to 280 problems.
These are the types of eslint errors this fixes:
Before adding this change working in test files looked like this:
Before change this is how many problems `yarn lint` showed:
After change this is how many problems `yarn lint` showed:
> [FIX] Add eslitn cypress package

- packages/app-shell/src/common/hooks/useUserTracker.test.js
- packages/app-shell/src/common/hooks/utils/segmentTraitGetters.js
- packages/app-shell/src/common/hooks/utils/segmentTraitGetters.test.js
Follow up to https://github.com/bufferapp/core-authentication-service/pull/1256/, to make sure we are not tracking as MP an org that is trialing.
> fix isMultiProductCustomer trait

- packages/app-shell/src/components/Modal/modals/PaidMigration/EssentialsPlan/index.jsx
- packages/app-shell/src/components/Modal/modals/PaidMigration/EssentialsPricing/index.jsx
- packages/app-shell/src/components/Modal/modals/PaidMigration/Intro/index.jsx
Track views on the various stages of the OB migration modal. 
NOTE: I've added the tracker to the first 3 stages but left out of the last (Success) one as I thought it might not be valuable to track views for it. Let me know if that's not the case 🙂
> Track when the OB migration modal is viewed

- packages/app-shell/babel.config.json
- packages/app-shell/package.json
- yarn.lock
It looks like [running two frontend apps with styled-components can lead to style collision](https://github.com/styled-components/styled-components/issues/2974#issuecomment-786990647), and it's recommended to process each bundle with `babel-plugin-styled-components` and `displayName: true`.
This seems to be what was causing the issue in production for Start Pages.
Context:
- Slack [link](https://buffer.slack.com/archives/C0YS0TW5P/p1631752164345900)
- Paper [link](https://paper.dropbox.com/doc/SP-prod-vs-dev-style-collision-investigation--BScpeC1SxU6A1mWLc8IdRzImAg-5ata9YNaynVGaIvr5ZGNL)
> Append displayName to styles to prevent style collision

- .eslintrc.js
- packages/app-shell/package.json
- packages/app-shell/src/common/hooks/useStartTrial.js
- packages/app-shell/src/common/hooks/useUpdateSubscriptionPlan.js
- packages/app-shell/src/components/Modal/index.jsx
- packages/app-shell/src/components/Modal/modals/PaymentMethod/hooks/useUpdateUserPaymentMethod.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/exports/Navigator/index.jsx
- yarn.lock
Prevent double rendering of the confirmation modal, that was caused by Account query refreshing after the mutation was completed.
fixes: [PUB-3836](https://buffer.atlassian.net/browse/PUB-3836)
> improve animation of the plan selector confirmation modal [PUB-3836]

- packages/app-shell/src/components/Modal/modals/PaidMigration/EssentialsPricing/index.jsx
This change removes confusion around using the word monthly when the
user is on a yearly plan
TIcket: https://buffer.atlassian.net/browse/GROW-261
Manual testing:
The below scenarios were both tested by impersonating 2 different users locally in app shell against production.
> [FIX] Change copy for Migrate to Essentials

- packages/app-shell/src/components/NavBar/index.jsx
- packages/app-shell/src/components/NavBar/index.test.js
- packages/app-shell/src/exports/Navigator/index.jsx
This ensures that any query parameters are properly passed down to the redirect URL for users without an active session.
You can test this out in here https://fix-logout-redirect-appshell.dev.buffer.com/?foo=foo&bar=bar
- This is a follow-up to the work started in https://github.com/bufferapp/buffer-publish/pull/1761.
- This issue was reported by @mallen5311 via Slack: https://buffer.slack.com/archives/CHRPK6R6D/p1617728115071500
- This is passing down the parameters to the login service, but those are getting stripped down when logging in, so we will need additional work if we want to persist those parameters after the login.
> append query parameters to logout redirect

- packages/app-shell/src/components/NavBar/utils/dropdown-items.js
Advocacy is conducting a two-week experiment in which we change the Navigator's "Help" menu items and show a survey for any customers interested in Live Chat. The Live Chat survey is triggered by our Pendo integration, which targets the class for the Live Chat menu item. 
https://buffer.atlassian.net/browse/TOOLS-156
**Changes**
- Remove `Visit Help Center` menu item
- Rename `Quick Help` menu item to `Help Center`
- Add `Live Chat` menu item
**Demo**
**Note**
The Pendo survey won't appear in the branch deploy for this PR, as Pendo is not installed in our staging environment. If you need to test the full flow (don't feel you have to), you'll need access to Pendo. Reach out to #help-tools or #prod-core-tools in Slack for access. Once you have access, you can follow the directions I've …
> [TOOLS-156] Live Chat Experiment

- packages/app-shell/src/components/NavBar/utils/dropdown-items.js
Reverts bufferapp/app-shell#129
The live chat experiment is ending on Wednesday, November 17th, so we should revert the App Shell back to its previous state.
[Jira ticket](https://buffer.atlassian.net/browse/TOOLS-187)
> [TOOLS-187] Remove Live Chat Experiment

- packages/app-shell/src/exports/Navigator/getTrialBannerCopy.jsx
- packages/app-shell/src/exports/Navigator/getTrialBannerCopy.test.jsx
- packages/app-shell/src/exports/Navigator/index.jsx
Extracted the copy to a function and added a test.
The `planName` is coming from here: 
https://github.com/bufferapp/core-authentication-service/blob/bbe172d413aa32ac744effc155665e3b0f9bd332/shared/services/billing/interfaces.ts#L23-L28
Tested locally:
> [GROW-306] extract trial banner copy to a function

- packages/app-shell/src/common/hooks/useModal.js
- packages/app-shell/src/common/hooks/useModal.test.js
- packages/app-shell/src/components/NavBar/index.jsx
- packages/app-shell/src/components/NavBar/index.test.js
We have some hashes that we can use in the buffer URLs which will trigger the Plan Selector and the Plan Migrator modal. Those are often used by customer advocates in order to provide a link to the users that they can use to self upgrade/downgrade or migrate. 
When a user is not authenticated we redirect them to the login service, which receives the current URL slightly modified (and verified) as a redirect URL. 
So far by trimming the hash from the URL, we were preventing the modal to open after the user have logged in successfully. 
This requires a small change in the account app as well since it overrides the redirect of the app shell. 
https://buffer.atlassian.net/browse/GROW-177
NOTE: Most of the changes are prettier formatting. The actual code changes are in …
> [GROW-177] Do not remove the modal hash from the URL and return it to login redirect

- packages/app-shell/src/components/NavBar/index.jsx
While testing the redirect changes I introduced in a previous PR (https://github.com/bufferapp/app-shell/pull/144), I noticed that the account menu item is passing a username and a redirect parameter that to my understanding does not seem useful. Additionally, it has the potential to create a bit weird recursive redirect URLs, like the following.
`https://account.buffer.com/?redirect=https://account.buffer.com/?redirect=https://account.buffer.com/?redirect=https://analyze.buffer.com&username=undefined`
The above is the result of consecutive clicks on the account menu item.
> Clean the account-app menu item url

- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useSelectedPlan.test.jsx
- packages/app-shell/src/components/Modal/utils.js
- packages/app-shell/src/components/Modal/utils.test.jsx
This now pre-selects the trial plan when opening the plan selector modal.
Testing instructions:
1. Make sure the user your using is on a trial
2. Click the "Strat subscription" button in the banner (see image 1 for ref)
3. The plan selector modal should open and the plan which you are trialing out should now be selected by default.
**What was happening before this change?**
When a user would click that "Start subscription" button the modal would open and pre-select the essentials plan as default.
1. Start subscription button
Video showing what we're fixing, the working code, and a brief explanation of some of the code 🙂
https://www.loom.com/share/e61ebd27eccf41faa3321db2b2f7c5d3
> [UPDATE] When on trial click start sub default

- packages/app-shell/src/components/Modal/modals/PlanSelector/components/AgencyPlanSection.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/AgencyPlanSection.style.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/FreePlanSection.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/components/FreePlanSection.style.js
Removing `slot-based-billing` split check for toggling between free and agency as we released agency to 100%.
Before
After
> [GROW-347] remove split check for agency

- packages/app-shell/src/components/Modal/index.jsx
- packages/app-shell/src/components/NavBar/index.jsx
This prevents modals from hiding the navigation bar, following the design defined in [Figma](https://www.figma.com/file/ugvq6I5lJ07W1aJBJg4ihm/Onboarding-2022?node-id=1016%3A65416)
> do not hide the navigation when modals are open

- packages/app-shell/package.json
- packages/app-shell/src/exports/Navigator/ErrorBoundary.jsx
- packages/app-shell/src/exports/Navigator/index.jsx
- yarn.lock
Created a new project in Bugsnag for [App Shell](https://app.bugsnag.com/buffer/app-shell/errors?filters[event.since]=30d&filters[error.status]=open&sort=last_seen)
This will enable Bugsnag only for `production` and `staging`.
This will also push errors to the Slack channel [#alerts-appshell](https://buffer.slack.com/archives/C034AEHFX9U/)
Tested locally, here's an [example of error](https://app.bugsnag.com/buffer/app-shell/errors/62176b77b1a02900082c4638?filters[event.since]=30d&filters[error.status]=open)
This is just a basic integration, there is more to do:
- Enable source maps so its easier to debug.
- Move API key to webpack environment var or somewhere else.
> [GROW-393] Add Bugsnag to app-shell

- packages/app-shell/webpack.config.dev.js
Sets `process.env.NODE_ENV` for development. 
We noticed that local development errors are alerting in Bugsnag ([Slack Thread](https://buffer.slack.com/archives/CPP95LDP1/p1646044554715609)). This sets  `development` as the environment when working locally to prevent these errors from reporting.
> Set NODE_ENV for development

- packages/app-shell/package.json
- packages/app-shell/src/common/hooks/useModal.js
- packages/app-shell/src/common/hooks/useSuggestedPlan.js
- packages/app-shell/src/components/Modal/index.jsx
- packages/app-shell/src/components/Modal/modals/Paywall/components/AnalyticsContent.jsx
- packages/app-shell/src/components/Modal/modals/Paywall/components/Ctas.jsx
- packages/app-shell/src/components/Modal/modals/Paywall/components/EngagementContent.jsx
- packages/app-shell/src/components/Modal/modals/Paywall/index.jsx
- packages/app-shell/src/components/Modal/modals/Paywall/styles.jsx
- packages/app-shell/src/components/Modal/modals/StartTrial/index.jsx
- packages/app-shell/src/components/Modal/utils.js
- packages/app-shell/src/components/Modal/utils.test.jsx
- packages/app/src/App.js
- yarn.lock
This adds the Analytics and Engagement Paywall modals for Free users
[WEBAPP-308](https://buffer.atlassian.net/browse/WEBAPP-308)
_Note: it replaces the modals added in https://github.com/bufferapp/buffer-analyze/pull/1151, and https://github.com/bufferapp/buffer-engage-client/pull/286 so that we can directly trigger the upgrade action._
> Webapp 378 paywall modal

- packages/app-shell/src/components/Modal/modals/PlanSelector/components/PlanSelectorContainer.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useButtonOptions.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useButtonOptions.test.jsx
🚢  This PR allows users to update plans with the new amount of channels but stay on the same plan.
Jira ticket: https://buffer.atlassian.net/browse/GROW-387
This includes new unit tests to cover updates to existing functions
> [UPDATE] Allow plan update when only quantity is changed

- cypress/fixtures/accountObEssential.json
- cypress/fixtures/accountObEssentialNoChannels.json
- cypress/fixtures/accountObFree.json
- cypress/fixtures/accountObTeam.json
- packages/app-shell/src/common/graphql/account.js
- packages/app-shell/src/common/hooks/useEmailVerification.js
- packages/app-shell/src/components/Banner/index.jsx
- packages/app-shell/src/exports/Navigator/components/EmailVerificationBanner/EmailVerificationBanner.jsx
- packages/app-shell/src/exports/Navigator/components/EmailVerificationBanner/index.js
- packages/app-shell/src/exports/Navigator/components/EmailVerificationBanner/styles.js
- packages/app-shell/src/exports/Navigator/index.jsx
This PR:
- Adds a banner for users to re-send email verifications is their account returns with `shouldShowEmailVerificationCommunication`
- Adds a `dismissible` prop for the `Banner` component to remove the ability to dismiss a banner. For example, if a user were to dismiss the email verification banner, the expected behavior is that it would prevent it from appearing again, but as soon as the page refreshes they would see it. Hiding the ability to dismiss it makes it feel like a better UX in that scenario. The default is to allow dismissing, so you need to explicitly remove it. 
- Adds a check that an action is provided, otherwise don't show a button. 
https://buffer.atlassian.net/browse/COREP-610
https://github.com/bufferapp/core-authentication-service/pull/1566 …
> [COREP-610] Display email verification required banner

- cypress.json
- packages/app-shell/src/exports/Navigator/components/EmailVerificationBanner/EmailVerificationBanner.jsx
Updates the email verification banner copy for better UX:
Related Slack thread: https://buffer.slack.com/archives/C6JL89JG6/p1646660985383169?thread_ts=1646655318.471679&cid=C6JL89JG6
> Update e-mail verification banner copy to provide more clarity for users

- cypress/fixtures/accountObFreeUpgrade.json
This fixes a failing cypress test. 
Message posted about issue here: https://buffer.slack.com/archives/C0DLE125Q/p1646669562408999
The fix required added a missing value to the mock user account for the cypress test.
> [UPDATE] add missing value to mock accont

- packages/app-shell/src/components/Modal/modals/Summary/components/UpdatedPlanInfo.jsx
🚢  Fix wording in updated billing section to match with selected plan cycle
> [FIX] Typo in billing text

- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useButtonOptions.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useButtonOptions.test.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useHeaderLabel.js
- packages/app-shell/src/components/Modal/modals/PlanSelector/hooks/useHeaderLabel.test.jsx
Updating some copy and a CTA to be less confusing from `Confirm Trial Plan` to `Confirm Plan`.
> [GROW-405] Update Confirm Trial Plan to Confirm Plan to be less confusing

- packages/app-shell/src/common/hooks/useModal.js
- packages/app-shell/src/components/Modal/modals/Confirmation/getCopy.jsx
- packages/app-shell/src/components/Modal/modals/Confirmation/index.jsx
- packages/app-shell/src/components/Modal/modals/PlanSelector/index.jsx
This piece of code is listening to a modal change within the navigator and emits an event with this modal (`ACTIONS.openModal` runs the event dispatcher). 
This event can be listened to by the different products and refresh the organization data and therefore the organization information on the various pages.
Essentially, this will be triggered when we successfully have updated a plan and on the account app, if we listen to and act to this event, we can update the Billing and the Channels page, without a hard refresh. 
@gisete I believe that we could reuse this (or a similar) approach for the quantity modal as well. 
@daisymarie128 I changed the part where we update only the quantity and the plan remains the same. The reason was that I was becoming a bit tricky to trigger a success event …
> [GROW-411] Emits a modal event on success modal

- packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
Updating `New monthly cost` to `New cost`
The description below already have the information: `planCycle` can be either `month` or `year`
https://github.com/bufferapp/app-shell/blob/d552c43d83a99a697d47a9aacfea0faa086b6cb5/packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx#L116
> [GROW-423] update copy

- packages/app-shell/src/components/Modal/modals/Confirmation/index.jsx
🚢  [GROW-435](https://buffer.atlassian.net/browse/GROW-435)
This pr adjusts the sizing of the success modal.
There are 2 states for this modal now:
1. User changed plans - they see congratulations on changing to you new plan etc (larger messaging - what we originally had before SBB)
2. Success modal for when a user stays on the same plan but only updates channel quantity - this messaging is far shorter and looked funny with the large modal size
After this change, I have adjusted some of the CSS to make the modal look cleaner and add a conditional for the 2 states to make the sizing different for both.
Includes adding proptypes to component
> [UPDATE] Adjust sizing for stayed on same plan and original

- cypress/fixtures/accountObEssential.json
- cypress/fixtures/accountObEssentialNoChannels.json
- cypress/fixtures/accountObFree.json
- cypress/fixtures/accountObFreeUpgrade.json
- cypress/fixtures/accountObTeam.json
- packages/app-shell/src/common/graphql/account.js
- packages/app-shell/src/common/hooks/useOrgSwitcher.js
We do some manual cache changes when an organization is switched in
order to prevent over-fetching but if the fields in both
currentOrganization and organizations are not the same the query
write will fail to validate and break.
Using a fragment ensures that we request the same fields on both edges.
> fix: use AccountOrganizationFiels fragment to prevent missing props

- packages/app-shell/src/components/Modal/modals/Summary/components/UpdatedPlanInfo.style.js
`slot-based-billing` OFF
`slot-based-billing` ON - before
`slot-based-billing` ON - after
> [GROW-440] remove top border summary

- packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> [GROW-384] use full cycle name instead of abbreviation & update copy

- packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
We were raising the error but never displaying it.
To test in dev, we can just add extra characters to the ID we use in the call to Stripe:
```
await stripeClientLatest.subscriptionItems.update(
// the gateway id is the stripe subscription item
`${customer.subscription.plan.gatewayId}123`,
{
quantity: SubscriptionQuantity.newStrict(quantity),
proration_behavior: prorationBehaviour,
},
)
```
https://github.com/bufferapp/core-authentication-service/blob/83b06046e572788a20b199a7901dcdd50bac7b01/shared/services/billing/gateways/StripeGateway/StripeGateway.updateSubscriptionQuantity.ts#L28-L35
Not sure where to display it,I added it under the description. Let me know if you think there is a better positioning.
> [GROW-439] Surface error message

- packages/app-shell/src/components/Modal/modals/PlanSelector/style.js
I noticed that for Agency plans, the saving copy is on 2 lines instead of 1 for the rest.
Before
After
> increase width for saving copy to be on one line

- packages/app-shell/src/components/Modal/modals/QuantityUpdate/components/CardBody.jsx
> [GROW-452] add currently paying amount to quantity modal
